[package]
name = "balthaproto"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.4"
prost = "0.6.1"
futures_codec = "0.4.0"
libp2p = "0.15.0"
futures = "0.3.2"

[build-dependencies]
prost-build = "0.6.1"
