[package]
name = "balthalib"
version = "0.0.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
balthernet = { path = "../balthernet" }
balthastore = { path = "../balthastore" }