[package]
name = "balthalib"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]

[dependencies]
tokio = "=0.1.11"
serde_derive = "1.0.80"
serde = "1.0.80"
ron = "0.4.0"

balthacephalo = { path = "../balthacephalo" }
balthapode = { path = "../balthapode" }
balthernet = { path = "../balthernet" }
