[package]
name = "balthalib"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]

[dependencies]
balthacephalo = { path = "../balthacephalo" }
balthapode = { path = "../balthapode" }
balthernet = { path = "../balthernet" }
