[package]
name = "balthalib"
version = "0.1.1"
authors = ["GONI Guillaume <gdn3@live.fr>"]

[dependencies]
tokio = "0.1.22"
serde_derive = "1.0.101"
serde = "1.0.101"
ron = "0.5.1"

balthacephalo = { path = "../balthacephalo" }
balthapode = { path = "../balthapode" }
balthernet = { path = "../balthernet" }
