[package]
name = "balthachain"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
balthamisc = { path = "../balthamisc" }
balthaproto = { path = "../balthaproto" }
web3 = "0.10.0"
futures = { version = "0.3.4", features = ["compat"] }
ethabi = "11.0.0"
