[workspace]
name = "balthazar"
version = "0.0.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]

members = [
    "balthacli",
    "balthalib",
    "balthernet",
    "balthastore",
    "balthaproto",
]

default-members = ["balthacli"]