[workspace]
# name = "balthazar"
# version = "0.1.0"
# authors = ["GONI Guillaume <gdn3@live.fr>"]

members = [
    "balthacli",
    "balthalib",
    "balthernet",
    "balthastore",
    "balthaproto",
    "balthamisc",
    "balthurner",
]

default-members = ["balthacli"]
