[package]
name = "balthamisc"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.13", features = ["sync"] }
futures = "0.3.4"
multiaddr = "0.3.1"
multihash = "0.10.0"
multibase = "0.8.0"
