[package]
name = "balthapode"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]

[dependencies]
parity-wasm = "0.32.0"
wasmi = "0.4.0"

balthajob = { path = "../balthajob" }
balthmessage = { path = "../balthmessage" }
balthernet = { path = "../balthernet" }
