[package]
name = "balthapode"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]

[dependencies]
tokio = "=0.1.11"
futures = "0.1.25"
parity-wasm = "0.35.1"
wasmi = "0.4.2"

balthajob = { path = "../balthajob" }
balthmessage = { path = "../balthmessage" }
balthernet = { path = "../balthernet" }
