[package]
name = "balthajob"
version = "0.2.3"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

[dependencies]
serde_derive = "1.0.101"
serde = "1.0.101"
parity-wasm = "0.37.0"
wasmi = "0.5.1"
sha3 = "0.8.2"
ron = "0.5.1"
