[package]
name = "balthmessage"
version = "0.3.1"
authors = ["GONI Guillaume <gdn3@live.fr>"]

[dependencies]
serde_derive = "1.0.101"
serde = "1.0.101"
ron = "0.5.1"
tokio = "0.1.22"
bytes = "0.4.12"
rand= "0.7.2"

balthajob = { path = "../balthajob" }
