[package]
name = "balthmessage"
version = "0.2.4"
authors = ["GONI Guillaume <gdn3@live.fr>"]

[dependencies]
serde_derive = "1.0.88"
serde = "1.0.88"
ron = "0.4.1"
tokio = "0.1.15"
bytes = "0.4.11"
rand= "0.6.5"

balthajob = { path = "../balthajob" }
