[package]
name = "balthmessage"
version = "0.3.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]

[dependencies]
serde_derive = "1.0.89"
serde = "1.0.89"
ron = "0.4.2"
tokio = "0.1.18"
bytes = "0.4.12"
rand= "0.6.5"

balthajob = { path = "../balthajob" }
