[package]
name = "balthmessage"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]

[dependencies]
serde_derive = "1.0.78"
serde = "1.0.78"
ron = "0.4.0"

balthajob = { path = "../balthajob" }
