[package]
name = "balthnative"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

[dependencies]
sha3 = "0.8.1"
serde_derive = "1.0.89"
serde = "1.0.89"
ron = "0.4.2"

balthajob = { path = "../balthajob" }
