[package]
name = "balthnative"
version = "0.1.1"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

[dependencies]
sha3 = "0.8.2"
serde_derive = "1.0.101"
serde = "1.0.101"
ron = "0.5.1"

balthajob = { path = "../balthajob" }
