[package]
name = "balthernet"
version = "0.2.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
balthaproto = { path = "../balthaproto" }
balthamisc = { path = "../balthamisc" }
libp2p = "0.16.2"
futures = "0.3.4"
void = "1.0.2"
tokio = { version = "0.2.12", features = ["sync"] }
