[package]
name = "balthernet"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = "0.15.0"
balthaproto = { path = "../balthaproto" }
balthamisc = { path = "../balthamisc" }
futures = "0.3.1"
# TODO: restrict features to bare essentials.
# tokio = { version = "0.2.11", features = ["full"] }
