[package]
name = "balthernet"
version = "0.2.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

[dependencies]
serde = "1.0.80"
ron = "0.4.0"
tokio = "0.1.13"
futures = "0.1.25"
bytes = "0.4.11"
rand= "0.6.1"
libsecp256k1= "0.2.1"

balthmessage = { path = "../balthmessage" }