[package]
name = "balthernet"
version = "0.4.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

[dependencies]
serde = "1.0.88"
ron = "0.4.1"
tokio = "0.1.15"
futures = "0.1.25"
bytes = "0.4.11"
rand= "0.6.5"
libsecp256k1= "0.2.2"

balthmessage = { path = "../balthmessage" }
