[package]
name = "balthernet"
version = "0.4.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

[dependencies]
serde = "1.0.89"
ron = "0.4.2"
tokio = "0.1.18"
futures = "0.1.25"
bytes = "0.4.12"
rand= "0.6.5"
libsecp256k1= "0.2.2"

balthmessage = { path = "../balthmessage" }
