[package]
name = "balthastore"
version = "0.2.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipfs-api = "0.6.0-rc"
futures = "0.3.2"
http = "0.2.0"
bytes = "0.5.4"
tokio = { version = "0.2.11", features = ["fs"] }
multiaddr = "0.3.1"
either = "1.5.3"
