[package]
name = "balthastore"
version = "0.3.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipfs-api = "0.7.2"
futures = "0.3.5"
http = "0.2.1"
bytes = "0.5.4"
tokio = { version = "0.2.21", features = ["fs"] }
parity-multiaddr = "0.8.0"
either = "1.5.3"
