[package]
name = "balthwasm"
version = "0.1.1"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
sha3 = "0.8.2"
serde_derive = "1.0.101"
serde = "1.0.101"
ron = "0.5.1"
