[package]
name = "balthwasm"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
sha3 = "0.8.0"
serde_derive = "1.0.80"
serde = "1.0.80"
ron = "0.4.0"
