[package]
name = "balthwasm"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
sha3 = "0.8.1"
serde_derive = "1.0.88"
serde = "1.0.88"
ron = "0.4.1"
