[package]
name = "balthurner"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-runtime = "0.14.0"
balthamisc = { path = "../balthamisc" }
either = "1.5.3"
bytes = "0.5.4"

[dev-dependencies]
futures = "0.3.4"
