[package]
name = "balthacephalo"
version = "0.1.0"
authors = ["GONI Guillaume <gdn3@live.fr>"]

[dependencies]
tokio = "0.1.15"

balthmessage = { path = "../balthmessage" }
balthajob = { path = "../balthajob" }
balthernet = { path = "../balthernet" }
